spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/simplepdm"
    driverClassName: org.postgresql.Driver
    username: "postgres"
    password: "postgres"
  flyway:
    locations: classpath:db/migration/ddl,classpath:db/migration/dml

springdoc:
  packagesToScan: ru.andri.simplepdm
  pathsToMatch: /**
